# Generated by Django 5.1.3 on 2025-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_host',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
