# Generated by Django 5.1.3 on 2025-02-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_tbl_host_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_host',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_host',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
