# Generated by Django 5.1.3 on 2025-02-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_alter_tbl_host_latitude_alter_tbl_host_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_host',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tbl_host',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tbl_host',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
