# Generated by Django 5.1.3 on 2025-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_remove_tbl_host_latitude_remove_tbl_host_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_host',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tbl_host',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
