# Generated by Django 5.1.3 on 2025-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_alter_tbl_host_latitude_alter_tbl_host_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_host',
            name='status',
            field=models.CharField(choices=[('personal_details_entered', 'Personal Details Entered'), ('property_details_entering', 'Property Details Entering'), ('file_uploaded', 'File Uploaded'), ('pending', 'Pending'), ('approved', 'approved')], default='personal_details_entered', max_length=50),
        ),
    ]
