# Generated by Django 5.1.3 on 2025-02-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_tbl_host_latitude_tbl_host_longitude'),
        ('userapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_guests', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_option', models.CharField(choices=[('cash_on_arrival', 'Cash on Arrival'), ('upi', 'UPI'), ('card', 'Card')], default='cash_on_arrival', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund')], default='pending', max_length=20)),
                ('booking_status', models.CharField(choices=[('booking_completed', 'Booking Completed'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('canceled', 'Canceled')], default='booking_completed', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='host.tbl_host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
