# Generated by Django 5.1.3 on 2025-02-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booking_initiated', 'Booking Initiated'), ('booking_completed', 'Booking Completed'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('canceled', 'Canceled')], default='', max_length=20),
        ),
    ]
