# Generated by Django 5.1.3 on 2025-02-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_booking_refund_amount_alter_booking_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_register',
            old_name='name',
            new_name='username',
        ),
    ]
