# Generated by Django 5.1.3 on 2025-03-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_register',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booking_initiated', 'Booking Initiated'), ('booking_completed', 'Booking Completed'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('canceled', 'Canceled')], default='booking_initiated', max_length=20),
        ),
    ]
